# Generated by Django 4.1.7 on 2023-03-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11),
        ),
    ]
